### ISSUE TITLE
Add larger sort buffer for MYSQL8 

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#140]
@aksm this needs to be added to the docker-compose file --sort_buffer_size because Mysql 8.022 has a BUG!

```YML
db:
   image: mysql:8.0.22
   command: mysqld --default-authentication-plugin=mysql_native_password  --max_allowed_packet=256M --sort_buffer_size=512K
````
