### ISSUE TITLE
Monolog as default logger for Archipelago, is the right way?

### ISSUE THREAD

**Issue by giancarlobi** [esmero/archipelago-deployment#86]
@DiegoPino I started to install Monolog on my Archipelago without docker Drupal 9.1. 
The steps I made are (probably you can do it better and with less steps, but this is the first try):
```
sudo -u www-data composer require 'monolog/monolog'
Using version ^2.2 for monolog/monolog

my private folder is /mnt/archicantadata so
mkdir /mnt/archicantadata/logs

nano -w web/sites/default/monolog.services.yml

parameters:
  monolog.channel_handlers:
    hydroponics: ['rotating_file_hydroponics']
    default: ['rotating_file']

services:
  monolog.handler.rotating_file_hydroponics:
    class: Monolog\Handler\RotatingFileHandler
    arguments: ['private://logs/hydroponics.log', 10, '%monolog.level.debug%']
  monolog.handler.rotating_file:
    class: Monolog\Handler\RotatingFileHandler
    arguments: ['private://logs/debug.log', 10, '%monolog.level.debug%']

chown www-data:www-data  web/sites/default/monolog.services.yml

nano -w web/sites/default/settings.php

/**
 * Enable Monolog service
 *
 */
$settings['container_yamls'][] = 'sites/default/monolog.services.yml';

sudo -u www-data /var/www/archipelago/vendor/drush/drush/drush cr

I missed drupal/monolog module !!!

sudo -u www-data composer require 'drupal/monolog:^2.0'
  - Installing drupal/monolog (2.0.0-beta2): Loading from cache

sudo -u www-data /var/www/archipelago/vendor/drush/drush/drush en monolog
 [success] Successfully enabled: monolog

sudo -u www-data /var/www/archipelago/vendor/drush/drush/drush cr 
```
From this moment, no more entry in Drupal dblog, all logs to `private://logs/debug.log` while adding `\Drupal::logger('hydroponics')->debug("some message here"); ` to HydroponicsDrushCommands.php message will be logged to private://logs/hydroponics.log.
I enabled rotating so log files are named as:
```
ls -l /mnt/archicantadata/logs/
total 16
-rw-r--r-- 1 www-data www-data 5940 Jan  5 12:18 debug-2021-01-05.log
-rw-r--r-- 1 www-data www-data 5431 Jan  5 12:20 hydroponics-2021-01-05.log
```

**Comment by giancarlobi** [comment]
This conf to send only channel hydroponics to external file while all other logs are sent to standard Drupal dblog
```
parameters:
  monolog.channel_handlers:
    hydroponics: ['rotating_file_hydroponics']
    default: ['drupal.dblog']

services:
  monolog.handler.rotating_file_hydroponics:
    class: Monolog\Handler\RotatingFileHandler
    arguments: ['private://logs/hydroponics.log', 10, '%monolog.level.debug%']
```
